#!/bin/bash

##
# check the tag name in CHANGELOG.md
# @use check_tag_name_in_changelog_me <tag name>
##
function check_tag_name_in_changelog_me() {
    # get the CHANGELOG from curreng tag name.
    # Navigate to the root of the repository
    REPO_ROOT=$(git rev-parse --show-toplevel)
    cd "$REPO_ROOT"

    # Get the contents of the CHANGELOG at the given tag
    local changeLog="CHANGELOG.md"
    local CHANGELOG_CONTENT=$(git show "$tag_name:${changeLog}")
    echo "${CHANGELOG_CONTENT}" | grep '^## ' 
    lastTagNameInChangeLog=$( echo "${CHANGELOG_CONTENT}" | grep '^## ' | tail -n 1 | cut -d ' ' -f 2 )
    echo "Check the tag name: ${tag_name}."

    # Check if the CHANGELOG has the change log for tag name
    if ! [[ "${tag_name}" == "v${lastTagNameInChangeLog}" ]]; then
        echo "Tag name $tag_name was not existed in ${changeLog}', please to add the change log for the tag name ${tag_name}. look like the belowing code:"
        cat <<EOF
## ${tag_name:1}
- feat: add some features for ${tag_name}
- fix: fix some issue for ${tag_name}
- chore: something unimportan.

EOF
            exit 1
        fi
    
}

##
# Check the tag name is valid 
# @use check_tag_name_valid <tag name>
##
function check_tag_name_valid() {
    # Check if tag name fits the pattern
    if ! [[ $tag_name =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]
    then
        echo "Tag name $tag_name does not match the pattern 'vX.Y.Z'"
        exit 1
    fi
}


tag_name="v0.0.2"
check_tag_name_in_changelog_me "${tag_name}"
# while read local_ref local_sha remote_ref remote_sha
# do
#     # Check if we are pushing tags
#     if [[ $local_ref == refs/tags/* ]]; then
#         # Extract the tag name
#         tag_name=${local_ref#refs/tags/}
#         check_tag_name_valid "${tag_name}"
#         check_tag_name_in_changelog_me "${tag_name}"
#     fi
# done