#!/bin/bash

ALL_LOCAL_TAGS=($(git tag))

. scripts/common.sh # {check_tag_name_exited_in_change_log}

##
# @Sumary check the branch name is existed in the local tags
# @params --branch-name {string} the branch name
# @return <boolean>
##
function check_branch_name_is_tag_name() {
    local branch_name=''
    for i in $@; do
        case $i in
            --branch-name) 
                branch_name=$2; 
                shift 2
            ;;
            *) 
                [[ -n $1 ]] && shift
            ;;
        esac
    done
    # check the branch name was existed or not in the local tags
    for local_tag in ${ALL_LOCAL_TAGS[@]}; do
        if [[ $local_tag == $branch_name ]]; then
            return 0
        fi
    done
    return 1
}

# Read from stdin to get the name of the branch being pushed
while read local_ref local_sha remote_ref remote_sha
do
  # Extract the local and remote branch names
  local_branch=$(echo $local_ref | sed -e 's,.*/\(.*\),\1,')
  # check the local branch name was existed or not in the local tags
    check_branch_name_is_tag_name --branch-name $local_branch
    if [[ $? == 0 ]]; then
        tagName="${local_branch}"
        echo "Detected that you are pushing a tag named ${tagName}"
        check_tag_name_exited_in_change_log --tag-name "$tagName"
    fi
done
